"""Auto-generated details from Free Exercise DB (Unlicense / public domain).
Source: github.com/yuhonas/free-exercise-db

Instructions are in English. ES UI shows a small "EN" note."""

EXERCISE_DETAILS: dict[str, dict] = {
    'Air_Bike': {
        "name": 'Air Bike',
        "primary": ['abdominals'],
        "secondary": [],
        "equipment": 'body only',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Lie flat on the floor with your lower back pressed to the ground. For this exercise, you will need to put your hands beside your head. Be careful however to not strain with the neck as you perform it. Now lift your shoulders into the crunch position.',
            'Bring knees up to where they are perpendicular to the floor, with your lower legs parallel to the floor. This will be your starting position.',
            'Now simultaneously, slowly go through a cycle pedal motion kicking forward with the right leg and bringing in the knee of the left leg. Bring your right elbow close to your left knee by crunching to the side, as you breathe out.',
            'Go back to the initial position as you breathe in.',
            'Crunch to the opposite side as you cycle your legs and bring closer your left elbow to your right knee and exhale.',
            'Continue alternating in this manner until all of the recommended repetitions for each side have been completed.',
        ],
    },
    'Alternate_Incline_Dumbbell_Curl': {
        "name": 'Alternate Incline Dumbbell Curl',
        "primary": ['biceps'],
        "secondary": ['forearms'],
        "equipment": 'dumbbell',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Sit down on an incline bench with a dumbbell in each hand being held at arms length. Tip: Keep the elbows close to the torso.This will be your starting position.',
            'While holding the upper arm stationary, curl the right weight forward while contracting the biceps as you breathe out. As you do so, rotate the hand so that the palm is facing up. Continue the movement until your biceps is fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps. Tip: Only the forearms should move.',
            'Slowly begin to bring the dumbbell back to starting position as your breathe in.',
            'Repeat the movement with the left hand. This equals one repetition.',
            'Continue alternating in this manner for the recommended amount of repetitions.',
        ],
    },
    'Arnold_Dumbbell_Press': {
        "name": 'Arnold Dumbbell Press',
        "primary": ['shoulders'],
        "secondary": ['triceps'],
        "equipment": 'dumbbell',
        "level": 'intermediate',
        "mechanic": 'compound',
        "instructions": [
            'Sit on an exercise bench with back support and hold two dumbbells in front of you at about upper chest level with your palms facing your body and your elbows bent. Tip: Your arms should be next to your torso. The starting position should look like the contracted portion of a dumbbell curl.',
            'Now to perform the movement, raise the dumbbells as you rotate the palms of your hands until they are facing forward.',
            'Continue lifting the dumbbells until your arms are extended above you in straight arm position. Breathe out as you perform this portion of the movement.',
            'After a second pause at the top, begin to lower the dumbbells to the original position by rotating the palms of your hands towards you. Tip: The left arm will be rotated in a counter clockwise manner while the right one will be rotated clockwise. Breathe in as you perform this portion of the movement.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Barbell_Bench_Press_-_Medium_Grip': {
        "name": 'Barbell Bench Press - Medium Grip',
        "primary": ['chest'],
        "secondary": ['shoulders', 'triceps'],
        "equipment": 'barbell',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Lie back on a flat bench. Using a medium width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.',
            'From the starting position, breathe in and begin coming down slowly until the bar touches your middle chest.',
            'After a brief pause, push the bar back to the starting position as you breathe out. Focus on pushing the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position at the top of the motion, hold for a second and then start coming down slowly again. Tip: Ideally, lowering the weight should take about twice as long as raising it.',
            'Repeat the movement for the prescribed amount of repetitions.',
            'When you are done, place the bar back in the rack.',
        ],
    },
    'Barbell_Curl': {
        "name": 'Barbell Curl',
        "primary": ['biceps'],
        "secondary": ['forearms'],
        "equipment": 'barbell',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Stand up with your torso upright while holding a barbell at a shoulder-width grip. The palm of your hands should be facing forward and the elbows should be close to the torso. This will be your starting position.',
            'While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Tip: Only the forearms should move.',
            'Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard.',
            'Slowly begin to bring the bar back to starting position as your breathe in.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Barbell_Deadlift': {
        "name": 'Barbell Deadlift',
        "primary": ['lower back'],
        "secondary": ['calves', 'forearms', 'glutes', 'hamstrings', 'lats', 'middle back', 'quadriceps', 'traps'],
        "equipment": 'barbell',
        "level": 'intermediate',
        "mechanic": 'compound',
        "instructions": [
            'Stand in front of a loaded barbell.',
            'While keeping the back as straight as possible, bend your knees, bend forward and grasp the bar using a medium (shoulder width) overhand grip. This will be the starting position of the exercise. Tip: If it is difficult to hold on to the bar with this grip, alternate your grip or use wrist straps.',
            'While holding the bar, start the lift by pushing with your legs while simultaneously getting your torso to the upright position as you breathe out. In the upright position, stick your chest out and contract the back by bringing the shoulder blades back. Think of how the soldiers in the military look when they are in standing in attention.',
            'Go back to the starting position by bending at the knees while simultaneously leaning the torso forward at the waist while keeping the back straight. When the weights on the bar touch the floor you are back at the starting position and ready to perform another repetition.',
            'Perform the amount of repetitions prescribed in the program.',
        ],
    },
    'Barbell_Squat': {
        "name": 'Barbell Squat',
        "primary": ['quadriceps'],
        "secondary": ['calves', 'glutes', 'hamstrings', 'lower back'],
        "equipment": 'barbell',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack to just below shoulder level. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it.',
            'Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.',
            'Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times and also maintain a straight back. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances discussed in the foot stances section).',
            'Begin to slowly lower the bar by bending the knees and hips as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees. Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.',
            'Begin to raise the bar as you exhale by pushing the floor with the heel of your foot as you straighten the legs again and go back to the starting position.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Barbell_Walking_Lunge': {
        "name": 'Barbell Walking Lunge',
        "primary": ['quadriceps'],
        "secondary": ['calves', 'glutes', 'hamstrings'],
        "equipment": 'barbell',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Begin standing with your feet shoulder width apart and a barbell across your upper back.',
            'Step forward with one leg, flexing the knees to drop your hips. Descend until your rear knee nearly touches the ground. Your posture should remain upright, and your front knee should stay above the front foot.',
            'Drive through the heel of your lead foot and extend both knees to raise yourself back up.',
            'Step forward with your rear foot, repeating the lunge on the opposite leg.',
        ],
    },
    'Bent_Over_Barbell_Row': {
        "name": 'Bent Over Barbell Row',
        "primary": ['middle back'],
        "secondary": ['biceps', 'lats', 'shoulders'],
        "equipment": 'barbell',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.',
            'Now, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight. At the top contracted position, squeeze the back muscles and hold for a brief pause.',
            'Then inhale and slowly lower the barbell back to the starting position.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Bent_Over_Two-Dumbbell_Row': {
        "name": 'Bent Over Two-Dumbbell Row',
        "primary": ['middle back'],
        "secondary": ['biceps', 'lats', 'shoulders'],
        "equipment": 'dumbbell',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'With a dumbbell in each hand (palms facing your torso), bend your knees slightly and bring your torso forward by bending at the waist; as you bend make sure to keep your back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The weights should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.',
            'While keeping the torso stationary, lift the dumbbells to your side (as you breathe out), keeping the elbows close to the body (do not exert any force with the forearm other than holding the weights). On the top contracted position, squeeze the back muscles and hold for a second.',
            'Slowly lower the weight again to the starting position as you inhale.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Bicycling_Stationary': {
        "name": 'Bicycling, Stationary',
        "primary": ['quadriceps'],
        "secondary": ['calves', 'glutes', 'hamstrings'],
        "equipment": 'machine',
        "level": 'beginner',
        "mechanic": None,
        "instructions": [
            'To begin, seat yourself on the bike and adjust the seat to your height.',
            'Select the desired option from the menu. You may have to start pedaling to turn it on. You can use the manual setting, or you can select a program to use. Typically, you can enter your age and weight to estimate the amount of calories burned during exercise. The level of resistance can be changed throughout the workout. The handles can be used to monitor your heart rate to help you stay at an appropriate intensity.',
        ],
    },
    'Bodyweight_Walking_Lunge': {
        "name": 'Bodyweight Walking Lunge',
        "primary": ['quadriceps'],
        "secondary": ['calves', 'glutes', 'hamstrings'],
        "equipment": None,
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Begin standing with your feet shoulder width apart and your hands on your hips.',
            'Step forward with one leg, flexing the knees to drop your hips. Descend until your rear knee nearly touches the ground. Your posture should remain upright, and your front knee should stay above the front foot.',
            'Drive through the heel of your lead foot and extend both knees to raise yourself back up.',
            'Step forward with your rear foot, repeating the lunge on the opposite leg.',
        ],
    },
    'Butterfly': {
        "name": 'Butterfly',
        "primary": ['chest'],
        "secondary": [],
        "equipment": 'machine',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Sit on the machine with your back flat on the pad.',
            'Take hold of the handles. Tip: Your upper arms should be positioned parallel to the floor; adjust the machine accordingly. This will be your starting position.',
            'Push the handles together slowly as you squeeze your chest in the middle. Breathe out during this part of the motion and hold the contraction for a second.',
            'Return back to the starting position slowly as you inhale until your chest muscles are fully stretched.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Cable_Crossover': {
        "name": 'Cable Crossover',
        "primary": ['chest'],
        "secondary": ['shoulders'],
        "equipment": 'cable',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'To get yourself into the starting position, place the pulleys on a high position (above your head), select the resistance to be used and hold the pulleys in each hand.',
            'Step forward in front of an imaginary straight line between both pulleys while pulling your arms together in front of you. Your torso should have a small forward bend from the waist. This will be your starting position.',
            'With a slight bend on your elbows in order to prevent stress at the biceps tendon, extend your arms to the side (straight out at both sides) in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms and torso should remain stationary; the movement should only occur at the shoulder joint.',
            'Return your arms back to the starting position as you breathe out. Make sure to use the same arc of motion used to lower the weights.',
            'Hold for a second at the starting position and repeat the movement for the prescribed amount of repetitions.',
        ],
    },
    'Cable_Crunch': {
        "name": 'Cable Crunch',
        "primary": ['abdominals'],
        "secondary": [],
        "equipment": 'cable',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Kneel below a high pulley that contains a rope attachment.',
            'Grasp cable rope attachment and lower the rope until your hands are placed next to your face.',
            'Flex your hips slightly and allow the weight to hyperextend the lower back. This will be your starting position.',
            'With the hips stationary, flex the waist as you contract the abs so that the elbows travel towards the middle of the thighs. Exhale as you perform this portion of the movement and hold the contraction for a second.',
            'Slowly return to the starting position as you inhale. Tip: Make sure that you keep constant tension on the abs throughout the movement. Also, do not choose a weight so heavy that the lower back handles the brunt of the work.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Calf_Press': {
        "name": 'Calf Press',
        "primary": ['calves'],
        "secondary": [],
        "equipment": 'machine',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Adjust the seat so that your legs are only slightly bent in the start position. The balls of your feet should be firmly on the platform.',
            'Select an appropriate weight, and grasp the handles. This will be your starting position.',
            'Straighten the legs by extending the knees, just barely lifting the weight from the stack. Your ankle should be fully flexed, toes pointing up. Execute the movement by pressing downward through the balls of your feet as far as possible.',
            'After a brief pause, reverse the motion and repeat.',
        ],
    },
    'Close-Grip_Barbell_Bench_Press': {
        "name": 'Close-Grip Barbell Bench Press',
        "primary": ['triceps'],
        "secondary": ['chest', 'shoulders'],
        "equipment": 'barbell',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Lie back on a flat bench. Using a close grip (around shoulder width), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.',
            'As you breathe in, come down slowly until you feel the bar on your middle chest. Tip: Make sure that - as opposed to a regular bench press - you keep the elbows close to the torso at all times in order to maximize triceps involvement.',
            'After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your triceps muscles. Lock your arms in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up.',
            'Repeat the movement for the prescribed amount of repetitions.',
            'When you are done, place the bar back in the rack.',
        ],
    },
    'Crunches': {
        "name": 'Crunches',
        "primary": ['abdominals'],
        "secondary": [],
        "equipment": 'body only',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Lie flat on your back with your feet flat on the ground, or resting on a bench with your knees bent at a 90 degree angle. If you are resting your feet on a bench, place them three to four inches apart and point your toes inward so they touch.',
            "Now place your hands lightly on either side of your head keeping your elbows in. Tip: Don't lock your fingers behind your head.",
            'While pushing the small of your back down in the floor to better isolate your abdominal muscles, begin to roll your shoulders off the floor.',
            "Continue to push down as hard as you can with your lower back as you contract your abdominals and exhale. Your shoulders should come up off the floor only about four inches, and your lower back should remain on the floor. At the top of the movement, contract your abdominals hard and keep the contraction for a second. Tip: Focus on slow, controlled movement - don't cheat yourself by using momentum.",
            'After the one second contraction, begin to come down slowly again to the starting position as you inhale.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Decline_Dumbbell_Bench_Press': {
        "name": 'Decline Dumbbell Bench Press',
        "primary": ['chest'],
        "secondary": ['shoulders', 'triceps'],
        "equipment": 'dumbbell',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Secure your legs at the end of the decline bench and lie down with a dumbbell on each hand on top of your thighs. The palms of your hand will be facing each other.',
            'Once you are laying down, move the dumbbells in front of you at shoulder width.',
            'Once at shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position.',
            'Bring down the weights slowly to your side as you breathe out. Keep full control of the dumbbells at all times. Tip: Throughout the motion, the forearms should always be perpendicular to the floor.',
            'As you breathe out, push the dumbbells up using your pectoral muscles. Lock your arms in the contracted position, squeeze your chest, hold for a second and then start coming down slowly. Tip: It should take at least twice as long to go down than to come up..',
            'Repeat the movement for the prescribed amount of repetitions of your training program.',
        ],
    },
    'Dips_-_Triceps_Version': {
        "name": 'Dips - Triceps Version',
        "primary": ['triceps'],
        "secondary": ['chest', 'shoulders'],
        "equipment": 'body only',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            "To get into the starting position, hold your body at arm's length with your arms nearly locked above the bars.",
            'Now, inhale and slowly lower yourself downward. Your torso should remain upright and your elbows should stay close to your body. This helps to better focus on tricep involvement. Lower yourself until there is a 90 degree angle formed between the upper arm and forearm.',
            'Then, exhale and push your torso back up using your triceps to bring your body back to the starting position.',
            'Repeat the movement for the prescribed amount of repetitions.',
        ],
    },
    'Dumbbell_Bicep_Curl': {
        "name": 'Dumbbell Bicep Curl',
        "primary": ['biceps'],
        "secondary": ['forearms'],
        "equipment": 'dumbbell',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            "Stand up straight with a dumbbell in each hand at arm's length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.",
            'Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps.',
            'Then, inhale and slowly begin to lower the dumbbells back to the starting position.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Dumbbell_Lunges': {
        "name": 'Dumbbell Lunges',
        "primary": ['quadriceps'],
        "secondary": ['calves', 'glutes', 'hamstrings'],
        "equipment": 'dumbbell',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Stand with your torso upright holding two dumbbells in your hands by your sides. This will be your starting position.',
            'Step forward with your right leg around 2 feet or so from the foot being left stationary behind and lower your upper body down, while keeping the torso upright and maintaining balance. Inhale as you go down. Note: As in the other exercises, do not allow your knee to go forward beyond your toes as you come down, as this will put undue stress on the knee joint. Make sure that you keep your front shin perpendicular to the ground.',
            'Using mainly the heel of your foot, push up and go back to the starting position as you exhale.',
            'Repeat the movement for the recommended amount of repetitions and then perform with the left leg.',
        ],
    },
    'EZ-Bar_Curl': {
        "name": 'EZ-Bar Curl',
        "primary": ['biceps'],
        "secondary": [],
        "equipment": 'e-z curl bar',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Stand up straight while holding an EZ curl bar at the wide outer handle. The palms of your hands should be facing forward and slightly tilted inward due to the shape of the bar. Keep your elbows close to your torso. This will be your starting position.',
            'Now, while keeping your upper arms stationary, exhale and curl the weights forward while contracting the biceps. Focus on only moving your forearms.',
            'Continue to raise the weight until your biceps are fully contracted and the bar is at shoulder level. Hold the top contracted position for a moment and squeeze the biceps.',
            'Then inhale and slowly lower the bar back to the starting position.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'EZ-Bar_Skullcrusher': {
        "name": 'EZ-Bar Skullcrusher',
        "primary": ['triceps'],
        "secondary": ['forearms'],
        "equipment": 'e-z curl bar',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Using a close grip, lift the EZ bar and hold it with your elbows in as you lie on the bench. Your arms should be perpendicular to the floor. This will be your starting position.',
            'Keeping the upper arms stationary, lower the bar by allowing the elbows to flex. Inhale as you perform this portion of the movement. Pause once the bar is directly above the forehead.',
            'Lift the bar back to the starting position by extending the elbow and exhaling.',
            'Repeat.',
        ],
    },
    'Elliptical_Trainer': {
        "name": 'Elliptical Trainer',
        "primary": ['quadriceps'],
        "secondary": ['calves', 'glutes', 'hamstrings'],
        "equipment": 'machine',
        "level": 'intermediate',
        "mechanic": None,
        "instructions": [
            'To begin, step onto the elliptical and select the desired option from the menu. Most ellipticals have a manual setting, or you can select a program to run. Typically, you can enter your age and weight to estimate the amount of calories burned during exercise. Elevation can be adjusted to change the intensity of the workout.',
            'The handles can be used to monitor your heart rate to help you stay at an appropriate intensity.',
        ],
    },
    'Face_Pull': {
        "name": 'Face Pull',
        "primary": ['shoulders'],
        "secondary": ['middle back'],
        "equipment": 'cable',
        "level": 'intermediate',
        "mechanic": 'compound',
        "instructions": [
            'Facing a high pulley with a rope or dual handles attached, pull the weight directly towards your face, separating your hands as you do so. Keep your upper arms parallel to the ground.',
        ],
    },
    'Front_Plate_Raise': {
        "name": 'Front Plate Raise',
        "primary": ['shoulders'],
        "secondary": [],
        "equipment": 'other',
        "level": 'intermediate',
        "mechanic": 'isolation',
        "instructions": [
            "While standing straight, hold a barbell plate in both hands at the 3 and 9 o'clock positions. Your palms should be facing each other and your arms should be extended and locked with a slight bend at the elbows and the plate should be down near your waist in front of you as far as you can go. Tip: The arms will remain in this position throughout the exercise. This will be your starting position.",
            'Slowly raise the plate as you exhale until it is a little above shoulder level. Hold the contraction for a second. Tip: make sure that you do not swing the weight or bend at the elbows. Your torso should remain stationary throughout the movement as well.',
            'As you inhale, slowly lower the plate back down to the starting position.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Hammer_Curls': {
        "name": 'Hammer Curls',
        "primary": ['biceps'],
        "secondary": [],
        "equipment": 'dumbbell',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Stand up with your torso upright and a dumbbell on each hand being held at arms length. The elbows should be close to the torso.',
            'The palms of the hands should be facing your torso. This will be your starting position.',
            'Now, while holding your upper arm stationary, exhale and curl the weight forward while contracting the biceps. Continue to raise the weight until the biceps are fully contracted and the dumbbell is at shoulder level. Hold the contracted position for a brief moment as you squeeze the biceps. Tip: Focus on keeping the elbow stationary and only moving your forearm.',
            'After the brief pause, inhale and slowly begin the lower the dumbbells back down to the starting position.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Hanging_Leg_Raise': {
        "name": 'Hanging Leg Raise',
        "primary": ['abdominals'],
        "secondary": [],
        "equipment": 'body only',
        "level": 'expert',
        "mechanic": 'isolation',
        "instructions": [
            'Hang from a chin-up bar with both arms extended at arms length in top of you using either a wide grip or a medium grip. The legs should be straight down with the pelvis rolled slightly backwards. This will be your starting position.',
            'Raise your legs until the torso makes a 90-degree angle with the legs. Exhale as you perform this movement and hold the contraction for a second or so.',
            'Go back slowly to the starting position as you breathe in.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Hyperextensions_Back_Extensions': {
        "name": 'Hyperextensions (Back Extensions)',
        "primary": ['lower back'],
        "secondary": ['glutes', 'hamstrings'],
        "equipment": 'other',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Lie face down on a hyperextension bench, tucking your ankles securely under the footpads.',
            'Adjust the upper pad if possible so your upper thighs lie flat across the wide pad, leaving enough room for you to bend at the waist without any restriction.',
            'With your body straight, cross your arms in front of you (my preference) or behind your head. This will be your starting position. Tip: You can also hold a weight plate for extra resistance in front of you under your crossed arms.',
            'Start bending forward slowly at the waist as far as you can while keeping your back flat. Inhale as you perform this movement. Keep moving forward until you feel a nice stretch on the hamstrings and you can no longer keep going without a rounding of the back. Tip: Never round the back as you perform this exercise. Also, some people can go farther than others. The key thing is that you go as far as your body allows you to without rounding the back.',
            'Slowly raise your torso back to the initial position as you inhale. Tip: Avoid the temptation to arch your back past a straight line. Also, do not swing the torso at any time in order to protect the back from injury.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Incline_Dumbbell_Curl': {
        "name": 'Incline Dumbbell Curl',
        "primary": ['biceps'],
        "secondary": [],
        "equipment": 'dumbbell',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Sit back on an incline bench with a dumbbell in each hand held at arms length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.',
            'While holding the upper arm stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second.',
            'Slowly begin to bring the dumbbells back to starting position as your breathe in.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Incline_Dumbbell_Flyes': {
        "name": 'Incline Dumbbell Flyes',
        "primary": ['chest'],
        "secondary": ['shoulders'],
        "equipment": 'dumbbell',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Hold a dumbbell on each hand and lie on an incline bench that is set to an incline angle of no more than 30 degrees.',
            'Extend your arms above you with a slight bend at the elbows.',
            'Now rotate the wrists so that the palms of your hands are facing you. Tip: The pinky fingers should be next to each other. This will be your starting position.',
            'As you breathe in, start to slowly lower the arms to the side while keeping the arms extended and while rotating the wrists until the palms of the hand are facing each other. Tip: At the end of the movement the arms will be by your side with the palms facing the ceiling.',
            'As you exhale start to bring the dumbbells back up to the starting position by reversing the motion and rotating the hands so that the pinky fingers are next to each other again. Tip: Keep in mind that the movement will only happen at the shoulder joint and at the wrist. There is no motion that happens at the elbow joint.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Incline_Dumbbell_Press': {
        "name": 'Incline Dumbbell Press',
        "primary": ['chest'],
        "secondary": ['shoulders', 'triceps'],
        "equipment": 'dumbbell',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Lie back on an incline bench with a dumbbell in each hand atop your thighs. The palms of your hands will be facing each other.',
            'Then, using your thighs to help push the dumbbells up, lift the dumbbells one at a time so that you can hold them at shoulder width.',
            'Once you have the dumbbells raised to shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position.',
            'Be sure to keep full control of the dumbbells at all times. Then breathe out and push the dumbbells up with your chest.',
            'Lock your arms at the top, hold for a second, and then start slowly lowering the weight. Tip Ideally, lowering the weights should take about twice as long as raising them.',
            'Repeat the movement for the prescribed amount of repetitions.',
            'When you are done, place the dumbbells back on your thighs and then on the floor. This is the safest manner to release the dumbbells.',
        ],
    },
    'Jogging_Treadmill': {
        "name": 'Jogging, Treadmill',
        "primary": ['quadriceps'],
        "secondary": ['glutes', 'hamstrings'],
        "equipment": 'machine',
        "level": 'beginner',
        "mechanic": None,
        "instructions": [
            'To begin, step onto the treadmill and select the desired option from the menu. Most treadmills have a manual setting, or you can select a program to run. Typically, you can enter your age and weight to estimate the amount of calories burned during exercise. Elevation can be adjusted to change the intensity of the workout.',
            'Treadmills offer convenience, cardiovascular benefits, and usually have less impact than jogging outside. A 150 lb person will burn almost 250 calories jogging for 30 minutes, compared to more than 450 calories running. Maintain proper posture as you jog, and only hold onto the handles when necessary, such as when dismounting or checking your heart rate.',
        ],
    },
    'Leg_Extensions': {
        "name": 'Leg Extensions',
        "primary": ['quadriceps'],
        "secondary": [],
        "equipment": 'machine',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'For this exercise you will need to use a leg extension machine. First choose your weight and sit on the machine with your legs under the pad (feet pointed forward) and the hands holding the side bars. This will be your starting position. Tip: You will need to adjust the pad so that it falls on top of your lower leg (just above your feet). Also, make sure that your legs form a 90-degree angle between the lower and upper leg. If the angle is less than 90-degrees then that means the knee is over the toes which in turn creates undue stress at the knee joint. If the machine is designed that way, either look for another machine or just make sure that when you start executing the exercise you stop going down once you hit the 90-degree angle.',
            'Using your quadriceps, extend your legs to the maximum as you exhale. Ensure that the rest of the body remains stationary on the seat. Pause a second on the contracted position.',
            'Slowly lower the weight back to the original position as you inhale, ensuring that you do not go past the 90-degree angle limit.',
            'Repeat for the recommended amount of times.',
        ],
    },
    'Leg_Press': {
        "name": 'Leg Press',
        "primary": ['quadriceps'],
        "secondary": ['calves', 'glutes', 'hamstrings'],
        "equipment": 'machine',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).',
            'Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Tip: Make sure that you do not lock your knees. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position.',
            'As you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle.',
            'Pushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale.',
            'Repeat for the recommended amount of repetitions and ensure to lock the safety pins properly once you are done. You do not want that platform falling on you fully loaded.',
        ],
    },
    'Lying_Leg_Curls': {
        "name": 'Lying Leg Curls',
        "primary": ['hamstrings'],
        "secondary": [],
        "equipment": 'machine',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Adjust the machine lever to fit your height and lie face down on the leg curl machine with the pad of the lever on the back of your legs (just a few inches under the calves). Tip: Preferably use a leg curl machine that is angled as opposed to flat since an angled position is more favorable for hamstrings recruitment.',
            'Keeping the torso flat on the bench, ensure your legs are fully stretched and grab the side handles of the machine. Position your toes straight (or you can also use any of the other two stances described on the foot positioning section). This will be your starting position.',
            'As you exhale, curl your legs up as far as possible without lifting the upper legs from the pad. Once you hit the fully contracted position, hold it for a second.',
            'As you inhale, bring the legs back to the initial position. Repeat for the recommended amount of repetitions.',
        ],
    },
    'Lying_Triceps_Press': {
        "name": 'Lying Triceps Press',
        "primary": ['triceps'],
        "secondary": [],
        "equipment": 'e-z curl bar',
        "level": 'intermediate',
        "mechanic": 'isolation',
        "instructions": [
            'Lie on a flat bench with either an e-z bar (my preference) or a straight bar placed on the floor behind your head and your feet on the floor.',
            'Grab the bar behind you, using a medium overhand (pronated) grip, and raise the bar in front of you at arms length. Tip: The arms should be perpendicular to the torso and the floor. The elbows should be tucked in. This is the starting position.',
            'As you breathe in, slowly lower the weight until the bar lightly touches your forehead while keeping the upper arms and elbows stationary.',
            'At that point, use the triceps to bring the weight back up to the starting position as you breathe out.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Machine_Bench_Press': {
        "name": 'Machine Bench Press',
        "primary": ['chest'],
        "secondary": ['shoulders', 'triceps'],
        "equipment": 'machine',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Sit down on the Chest Press Machine and select the weight.',
            'Step on the lever provided by the machine since it will help you to bring the handles forward so that you can grab the handles and fully extend the arms.',
            'Grab the handles with a palms-down grip and lift your elbows so that your upper arms are parallel to the floor to the sides of your torso. Tip: Your forearms will be pointing forward since you are grabbing the handles. Once you bring the handles forward and extend the arms you will be at the starting position.',
            'Now bring the handles back towards you as you breathe in.',
            'Push the handles away from you as you flex your pecs and you breathe out. Hold the contraction for a second before going back to the starting position.',
            'Repeat for the recommended amount of reps.',
            'When finished step on the lever again and slowly get the handles back to their original place.',
        ],
    },
    'Oblique_Crunches': {
        "name": 'Oblique Crunches',
        "primary": ['abdominals'],
        "secondary": [],
        "equipment": 'body only',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Lie flat on the floor with your lower back pressed to the ground. For this exercise, you will need to put one hand beside your head and the other to the side against the floor.',
            'Make sure your feet are elevated and resting on a flat surface.',
            'Now lift the shoulder in which your hand is touching your head.',
            'Simply elevate your shoulder and body upward until you touch your knee. For example, if you have your right hand besides your head, then you want to elevate your body upwards until your right elbow touches your left knee. The same variation can be applied doing the inverse and using your left elbow to touch your right knee.',
            'After your knee touches your elbow, lower your body until you have reached the starting position.',
            'Remember to breathe in during the eccentric (lowering) part of the exercise and to breathe out during the concentric (upward) part of the exercise.',
            'Continue alternating in this manner until all of the recommended repetitions for each side have been completed.',
        ],
    },
    'One-Arm_Dumbbell_Row': {
        "name": 'One-Arm Dumbbell Row',
        "primary": ['middle back'],
        "secondary": ['biceps', 'lats', 'shoulders'],
        "equipment": 'dumbbell',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Choose a flat bench and place a dumbbell on each side of it.',
            'Place the right leg on top of the end of the bench, bend your torso forward from the waist until your upper body is parallel to the floor, and place your right hand on the other end of the bench for support.',
            'Use the left hand to pick up the dumbbell on the floor and hold the weight while keeping your lower back straight. The palm of the hand should be facing your torso. This will be your starting position.',
            'Pull the resistance straight up to the side of your chest, keeping your upper arm close to your side and keeping the torso stationary. Breathe out as you perform this step. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. Also, make sure that the force is performed with the back muscles and not the arms. Finally, the upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the dumbbell; therefore do not try to pull the dumbbell up using the forearms.',
            'Lower the resistance straight down to the starting position. Breathe in as you perform this step.',
            'Repeat the movement for the specified amount of repetitions.',
            'Switch sides and repeat again with the other arm.',
        ],
    },
    'Plank': {
        "name": 'Plank',
        "primary": ['abdominals'],
        "secondary": [],
        "equipment": 'body only',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder.',
            'Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised.',
        ],
    },
    'Preacher_Curl': {
        "name": 'Preacher Curl',
        "primary": ['biceps'],
        "secondary": [],
        "equipment": 'barbell',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'To perform this movement you will need a preacher bench and an E-Z bar. Grab the E-Z curl bar at the close inner handle (either have someone hand you the bar which is preferable or grab the bar from the front bar rest provided by most preacher benches). The palm of your hands should be facing forward and they should be slightly tilted inwards due to the shape of the bar.',
            'With the upper arms positioned against the preacher bench pad and the chest against it, hold the E-Z Curl Bar at shoulder length. This will be your starting position.',
            'As you breathe in, slowly lower the bar until your upper arm is extended and the biceps is fully stretched.',
            'As you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the bar is at shoulder height. Squeeze the biceps hard and hold this position for a second.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Pullups': {
        "name": 'Pullups',
        "primary": ['lats'],
        "secondary": ['biceps', 'middle back'],
        "equipment": 'body only',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Grab the pull-up bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.',
            'As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.',
            'Pull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.',
            'After a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched.',
            'Repeat this motion for the prescribed amount of repetitions.',
        ],
    },
    'Pushups': {
        "name": 'Pushups',
        "primary": ['chest'],
        "secondary": ['shoulders', 'triceps'],
        "equipment": 'body only',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length.',
            'Next, lower yourself downward until your chest almost touches the floor as you inhale.',
            'Now breathe out and press your upper body back up to the starting position while squeezing your chest.',
            'After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed.',
        ],
    },
    'Reverse_Barbell_Curl': {
        "name": 'Reverse Barbell Curl',
        "primary": ['biceps'],
        "secondary": ['forearms'],
        "equipment": 'barbell',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Stand up with your torso upright while holding a barbell at shoulder width with the elbows close to the torso. The palm of your hands should be facing down (pronated grip). This will be your starting position.',
            'While holding the upper arms stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second as you squeeze the muscle.',
            'Slowly begin to bring the bar back to starting position as your breathe in.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Reverse_Flyes': {
        "name": 'Reverse Flyes',
        "primary": ['shoulders'],
        "secondary": [],
        "equipment": 'dumbbell',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'To begin, lie down on an incline bench with the chest and stomach pressing against the incline. Have the dumbbells in each hand with the palms facing each other (neutral grip).',
            'Extend the arms in front of you so that they are perpendicular to the angle of the bench. The legs should be stationary while applying pressure with the ball of your toes. This is the starting position.',
            'Maintaining the slight bend of the elbows, move the weights out and away from each other (to the side) in an arc motion while exhaling. Tip: Try to squeeze your shoulder blades together to get the best results from this exercise.',
            'The arms should be elevated until they are parallel to the floor.',
            'Feel the contraction and slowly lower the weights back down to the starting position while inhaling.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Reverse_Grip_Bent-Over_Rows': {
        "name": 'Reverse Grip Bent-Over Rows',
        "primary": ['middle back'],
        "secondary": ['biceps', 'lats', 'shoulders'],
        "equipment": 'barbell',
        "level": 'intermediate',
        "mechanic": 'compound',
        "instructions": [
            'Stand erect while holding a barbell with a supinated grip (palms facing up).',
            'Bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.',
            'While keeping the torso stationary, lift the barbell as you breathe out, keeping the elbows close to the body and not doing any force with the forearm other than holding the weights. On the top contracted position, squeeze the back muscles and hold for a second.',
            'Slowly lower the weight again to the starting position as you inhale.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Reverse_Grip_Triceps_Pushdown': {
        "name": 'Reverse Grip Triceps Pushdown',
        "primary": ['triceps'],
        "secondary": [],
        "equipment": 'cable',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Start by setting a bar attachment (straight or e-z) on a high pulley machine.',
            'Facing the bar attachment, grab it with the palms facing up (supinated grip) at shoulder width. Lower the bar by using your lats until your arms are fully extended by your sides. Tip: Elbows should be in by your sides and your feet should be shoulder width apart from each other. This is the starting position.',
            'Slowly elevate the bar attachment up as you inhale so it is aligned with your chest. Only the forearms should move and the elbows/upper arms should be stationary by your side at all times.',
            'Then begin to lower the cable bar back down to the original staring position while exhaling and contracting the triceps hard.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Romanian_Deadlift': {
        "name": 'Romanian Deadlift',
        "primary": ['hamstrings'],
        "secondary": ['calves', 'glutes', 'lower back'],
        "equipment": 'barbell',
        "level": 'intermediate',
        "mechanic": 'compound',
        "instructions": [
            'Put a barbell in front of you on the ground and grab it using a pronated (palms facing down) grip that a little wider than shoulder width. Tip: Depending on the weight used, you may need wrist wraps to perform the exercise and also a raised platform in order to allow for better range of motion.',
            'Bend the knees slightly and keep the shins vertical, hips back and back straight. This will be your starting position.',
            'Keeping your back and arms completely straight at all times, use your hips to lift the bar as you exhale. Tip: The movement should not be fast but steady and under control.',
            'Once you are standing completely straight up, lower the bar by pushing the hips back, only slightly bending the knees, unlike when squatting. Tip: Take a deep breath at the start of the movement and keep your chest up. Hold your breath as you lower and exhale as you complete the movement.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Seated_Cable_Rows': {
        "name": 'Seated Cable Rows',
        "primary": ['middle back'],
        "secondary": ['biceps', 'lats', 'shoulders'],
        "equipment": 'cable',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'For this exercise you will need access to a low pulley row machine with a V-bar. Note: The V-bar will enable you to have a neutral grip where the palms of your hands face each other. To get into the starting position, first sit down on the machine and place your feet on the front platform or crossbar provided making sure that your knees are slightly bent and not locked.',
            'Lean over as you keep the natural alignment of your back and grab the V-bar handles.',
            'With your arms extended pull back until your torso is at a 90-degree angle from your legs. Your back should be slightly arched and your chest should be sticking out. You should be feeling a nice stretch on your lats as you hold the bar in front of you. This is the starting position of the exercise.',
            'Keeping the torso stationary, pull the handles back towards your torso while keeping the arms close to it until you touch the abdominals. Breathe out as you perform that movement. At that point you should be squeezing your back muscles hard. Hold that contraction for a second and slowly go back to the original position while breathing in.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Seated_Calf_Raise': {
        "name": 'Seated Calf Raise',
        "primary": ['calves'],
        "secondary": [],
        "equipment": 'machine',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Sit on the machine and place your toes on the lower portion of the platform provided with the heels extending off. Choose the toe positioning of your choice (forward, in, or out) as per the beginning of this chapter.',
            'Place your lower thighs under the lever pad, which will need to be adjusted according to the height of your thighs. Now place your hands on top of the lever pad in order to prevent it from slipping forward.',
            'Lift the lever slightly by pushing your heels up and release the safety bar. This will be your starting position.',
            'Slowly lower your heels by bending at the ankles until the calves are fully stretched. Inhale as you perform this movement.',
            'Raise the heels by extending the ankles as high as possible as you contract the calves and breathe out. Hold the top contraction for a second.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Seated_Dumbbell_Press': {
        "name": 'Seated Dumbbell Press',
        "primary": ['shoulders'],
        "secondary": ['triceps'],
        "equipment": 'dumbbell',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Grab a couple of dumbbells and sit on a military press bench or a utility bench that has a back support on it as you place the dumbbells upright on top of your thighs.',
            'Clean the dumbbells up one at a time by using your thighs to bring the dumbbells up to shoulder height at each side.',
            'Rotate the wrists so that the palms of your hands are facing forward. This is your starting position.',
            'As you exhale, push the dumbbells up until they touch at the top.',
            'After a second pause, slowly come down back to the starting position as you inhale.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Seated_Leg_Curl': {
        "name": 'Seated Leg Curl',
        "primary": ['hamstrings'],
        "secondary": [],
        "equipment": 'machine',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Adjust the machine lever to fit your height and sit on the machine with your back against the back support pad.',
            'Place the back of lower leg on top of padded lever (just a few inches under the calves) and secure the lap pad against your thighs, just above the knees. Then grasp the side handles on the machine as you point your toes straight (or you can also use any of the other two stances) and ensure that the legs are fully straight right in front of you. This will be your starting position.',
            'As you exhale, pull the machine lever as far as possible to the back of your thighs by flexing at the knees. Keep your torso stationary at all times. Hold the contracted position for a second.',
            'Slowly return to the starting position as you breathe in.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Side_Lateral_Raise': {
        "name": 'Side Lateral Raise',
        "primary": ['shoulders'],
        "secondary": [],
        "equipment": 'dumbbell',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Pick a couple of dumbbells and stand with a straight torso and the dumbbells by your side at arms length with the palms of the hand facing you. This will be your starting position.',
            'While maintaining the torso in a stationary position (no swinging), lift the dumbbells to your side with a slight bend on the elbow and the hands slightly tilted forward as if pouring water in a glass. Continue to go up until you arms are parallel to the floor. Exhale as you execute this movement and pause for a second at the top.',
            'Lower the dumbbells back down slowly to the starting position as you inhale.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Smith_Machine_Bench_Press': {
        "name": 'Smith Machine Bench Press',
        "primary": ['chest'],
        "secondary": ['shoulders', 'triceps'],
        "equipment": 'machine',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Place a flat bench underneath the smith machine. Now place the barbell at a height that you can reach when lying down and your arms are almost fully extended. Once the weight you need is selected, lie down on the flat bench. Using a pronated grip that is wider than shoulder width, unlock the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.',
            'As you breathe in, come down slowly until you feel the bar on your middle chest.',
            'After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up.',
            'Repeat the movement for the prescribed amount of repetitions.',
            'When you are done, lock the bar back in the rack.',
        ],
    },
    'Smith_Machine_Incline_Bench_Press': {
        "name": 'Smith Machine Incline Bench Press',
        "primary": ['chest'],
        "secondary": ['shoulders', 'triceps'],
        "equipment": 'machine',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Place an incline bench underneath the smith machine. Place the barbell at a height that you can reach when lying down and your arms are almost fully extended. Once the weight you need is selected, lie down on the incline bench and make sure your upper chest is aligned with the barbell. Using a pronated grip (palms facing forward) that is wider than shoulder width, unlock the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.',
            'As you breathe in, come down slowly until you feel the bar on your upper chest.',
            'After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up.',
            'Repeat the movement for the prescribed amount of repetitions.',
            'When you are done, place the bar back in the rack.',
        ],
    },
    'Smith_Machine_Overhead_Shoulder_Press': {
        "name": 'Smith Machine Overhead Shoulder Press',
        "primary": ['shoulders'],
        "secondary": ['triceps'],
        "equipment": 'machine',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'To begin, place a flat bench (or preferably one with back support) underneath a smith machine. Position the barbell at a height so that when seated on the flat bench, the arms must be almost fully extended to reach the barbell.',
            'Once you have the correct height, sit slightly in behind the barbell so that there is an imaginary straight line from the tip of your nose to the barbell. Your feet should be stationary. Grab the barbell with the palms facing forward, unlock it and lift it up so that your arms are fully extended. This is the starting position.',
            'Slowly begin to lower the barbell until it is level with your chin while inhaling.',
            'Then lift the barbell back to the starting position using your shoulders while exhaling.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Standing_Barbell_Calf_Raise': {
        "name": 'Standing Barbell Calf Raise',
        "primary": ['calves'],
        "secondary": [],
        "equipment": 'barbell',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, step under the bar and place the bar on the back of your shoulders (slightly below the neck).',
            'Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.',
            'Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times as looking down will get you off balance and also maintain a straight back. The knees should be kept with a slight bend; never locked. This will be your starting position. Tip: For better range of motion you may also place the ball of your feet on a wooden block but be careful as this option requires more balance and a sturdy block.',
            'Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down.',
            'Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Standing_Biceps_Cable_Curl': {
        "name": 'Standing Biceps Cable Curl',
        "primary": ['biceps'],
        "secondary": [],
        "equipment": 'cable',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Stand up with your torso upright while holding a cable curl bar that is attached to a low pulley. Grab the cable bar at shoulder width and keep the elbows close to the torso. The palm of your hands should be facing up (supinated grip). This will be your starting position.',
            'While holding the upper arms stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second as you squeeze the muscle.',
            'Slowly begin to bring the curl bar back to starting position as your breathe in.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Standing_Dumbbell_Triceps_Extension': {
        "name": 'Standing Dumbbell Triceps Extension',
        "primary": ['triceps'],
        "secondary": [],
        "equipment": 'dumbbell',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'To begin, stand up with a dumbbell held by both hands. Your feet should be about shoulder width apart from each other. Slowly use both hands to grab the dumbbell and lift it over your head until both arms are fully extended.',
            'The resistance should be resting in the palms of your hands with your thumbs around it. The palm of the hands should be facing up towards the ceiling. This will be your starting position.',
            'Keeping your upper arms close to your head with elbows in and perpendicular to the floor, lower the resistance in a semicircular motion behind your head until your forearms touch your biceps. Tip: The upper arms should remain stationary and only the forearms should move. Breathe in as you perform this step.',
            'Go back to the starting position by using the triceps to raise the dumbbell. Breathe out as you perform this step.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Standing_Military_Press': {
        "name": 'Standing Military Press',
        "primary": ['shoulders'],
        "secondary": ['triceps'],
        "equipment": 'barbell',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Start by placing a barbell that is about chest high on a squat rack. Once you have selected the weights, grab the barbell using a pronated (palms facing forward) grip. Make sure to grip the bar wider than shoulder width apart from each other.',
            'Slightly bend the knees and place the barbell on your collar bone. Lift the barbell up keeping it lying on your chest. Take a step back and position your feet shoulder width apart from each other.',
            'Once you pick up the barbell with the correct grip length, lift the bar up over your head by locking your arms. Hold at about shoulder level and slightly in front of your head. This is your starting position.',
            'Lower the bar down to the collarbone slowly as you inhale.',
            'Lift the bar back up to the starting position as you exhale.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'T-Bar_Row_with_Handle': {
        "name": 'T-Bar Row with Handle',
        "primary": ['middle back'],
        "secondary": ['biceps', 'lats'],
        "equipment": 'barbell',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Position a bar into a landmine or in a corner to keep it from moving. Load an appropriate weight onto your end.',
            'Stand over the bar, and position a Double D row handle around the bar next to the collar. Using your hips and legs, rise to a standing position.',
            'Assume a wide stance with your hips back and your chest up. Your arms should be extended. This will be your starting position.',
            'Pull the weight to your upper abdomen by retracting the shoulder blades and flexing the elbows. Do not jerk the weight or cheat during the movement.',
            'After a brief pause, return to the starting position.',
        ],
    },
    'Tricep_Dumbbell_Kickback': {
        "name": 'Tricep Dumbbell Kickback',
        "primary": ['triceps'],
        "secondary": [],
        "equipment": 'dumbbell',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Start with a dumbbell in each hand and your palms facing your torso. Keep your back straight with a slight bend in the knees and bend forward at the waist. Your torso should be almost parallel to the floor. Make sure to keep your head up. Your upper arms should be close to your torso and parallel to the floor. Your forearms should be pointed towards the floor as you hold the weights. There should be a 90-degree angle formed between your forearm and upper arm. This is your starting position.',
            'Now, while keeping your upper arms stationary, exhale and use your triceps to lift the weights until the arm is fully extended. Focus on moving the forearm.',
            'After a brief pause at the top contraction, inhale and slowly lower the dumbbells back down to the starting position.',
            'Repeat the movement for the prescribed amount of repetitions.',
        ],
    },
    'Triceps_Pushdown': {
        "name": 'Triceps Pushdown',
        "primary": ['triceps'],
        "secondary": [],
        "equipment": 'cable',
        "level": 'beginner',
        "mechanic": 'isolation',
        "instructions": [
            'Attach a straight or angled bar to a high pulley and grab with an overhand grip (palms facing down) at shoulder width.',
            'Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the bar. This is your starting position.',
            'Using the triceps, bring the bar down until it touches the front of your thighs and the arms are fully extended perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.',
            'After a second hold at the contracted position, bring the bar slowly up to the starting point. Breathe in as you perform this step.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'Upright_Barbell_Row': {
        "name": 'Upright Barbell Row',
        "primary": ['shoulders'],
        "secondary": ['traps'],
        "equipment": 'barbell',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Grasp a barbell with an overhand grip that is slightly less than shoulder width. The bar should be resting on the top of your thighs with your arms extended and a slight bend in your elbows. Your back should also be straight. This will be your starting position.',
            'Now exhale and use the sides of your shoulders to lift the bar, raising your elbows up and to the side. Keep the bar close to your body as you raise it. Continue to lift the bar until it nearly touches your chin. Tip: Your elbows should drive the motion, and should always be higher than your forearms. Remember to keep your torso stationary and pause for a second at the top of the movement.',
            'Lower the bar back down slowly to the starting position. Inhale as you perform this portion of the movement.',
            'Repeat for the recommended amount of repetitions.',
        ],
    },
    'V-Bar_Pulldown': {
        "name": 'V-Bar Pulldown',
        "primary": ['lats'],
        "secondary": ['biceps', 'middle back', 'shoulders'],
        "equipment": 'cable',
        "level": 'intermediate',
        "mechanic": 'compound',
        "instructions": [
            'Sit down on a pull-down machine with a V-Bar attached to the top pulley.',
            'Adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.',
            'Grab the V-bar with the palms facing each other (a neutral grip). Stick your chest out and lean yourself back slightly (around 30-degrees) in order to better engage the lats. This will be your starting position.',
            'Using your lats, pull the bar down as you squeeze your shoulder blades. Continue until your chest nearly touches the V-bar. Exhale as you execute this motion. Tip: Keep the torso stationary throughout the movement.',
            'After a second hold on the contracted position, slowly bring the bar back to the starting position as you breathe in.',
            'Repeat for the prescribed number of repetitions.',
        ],
    },
    'Wide-Grip_Lat_Pulldown': {
        "name": 'Wide-Grip Lat Pulldown',
        "primary": ['lats'],
        "secondary": ['biceps', 'middle back', 'shoulders'],
        "equipment": 'cable',
        "level": 'beginner',
        "mechanic": 'compound',
        "instructions": [
            'Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.',
            'Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.',
            'As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.',
            'As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the bar; therefore do not try to pull down the bar using the forearms.',
            'After a second at the contracted position squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.',
            'Repeat this motion for the prescribed amount of repetitions.',
        ],
    },
}

def details_for(key: str) -> dict | None:
    """Return the details dict for a canonical exercise key, or None."""
    from exercise_images import EXERCISE_IMAGE
    slug = EXERCISE_IMAGE.get(key)
    return EXERCISE_DETAILS.get(slug) if slug else None
